name: mm_corewood_palisade_beacon
piecehammer: Hammer
m_name: $piece_mm_corewood_palisade_beacon
sizeMultiplier: 1
m_description: ''
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_forge
piecehammerCategory: CoreWood-Building
minStationLevel: 1
amount: 1
disabled: true
adminonly: false
comfort:
  comfort: 1
  comfortGroup: Fire
  comfortObject: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 800
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: false
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData:
  StartFuel: 1
  MaxFuel: 5
  SecPerFuel: 20000
  InfiniteFuel: false
  FuelType: Coal
  IgniteInterval: 0
  IgniteChance: 0
  IgniteSpread: 0
teleportWorldData: 
build:
- RoundLog:4:0:True
- Wood:2:0:True
- Iron:2:0:True
- Coal:5:0:True
